# LangFuse Simple Setup (without ClickHouse for now)
# Based on official LangFuse documentation

services:
  langfuse-server:
    image: langfuse/langfuse:2
    container_name: langfuse-server
    ports:
      - "3030:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@langfuse-db:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3030
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000
      # Disable ClickHouse for now
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
    depends_on:
      langfuse-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - langfuse-network

  langfuse-db:
    image: postgres:15
    container_name: langfuse-db
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=langfuse
      - POSTGRES_DB=langfuse
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langfuse -d langfuse"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - langfuse-network

volumes:
  langfuse_db_data:

networks:
  langfuse-network:
    driver: bridge